/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author bastian
 */
public class Cliente extends javax.swing.JPanel {

    /**
     * Creates new form Cliente
     */
    public Cliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_Cliente = new javax.swing.JLabel();
        Label_RUT = new javax.swing.JLabel();
        Label_ApPaterno = new javax.swing.JLabel();
        Label_ApMaterno = new javax.swing.JLabel();
        TextField_RUT = new javax.swing.JTextField();
        Label_Nombre1 = new javax.swing.JLabel();
        TextField_Nombre1 = new javax.swing.JTextField();
        Label_Direccion = new javax.swing.JLabel();
        TextField_Direccion = new javax.swing.JTextField();
        Label_CodPostal = new javax.swing.JLabel();
        Label_Telefono1 = new javax.swing.JLabel();
        TextField_Telefono1 = new javax.swing.JTextField();
        Label_Direccion1 = new javax.swing.JLabel();
        TextField_Direccion1 = new javax.swing.JTextField();
        TextField_ApPaterno2 = new javax.swing.JTextField();
        Label_Telefono2 = new javax.swing.JLabel();
        TextField_CodPostal1 = new javax.swing.JTextField();
        TextField_ApPaterno4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        Label_Cliente.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        Label_Cliente.setText("Cliente");

        Label_RUT.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Label_RUT.setText("RUT");

        Label_ApPaterno.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Label_ApPaterno.setText("Apellido Paterno");

        Label_ApMaterno.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Label_ApMaterno.setText("Apellido Materno");

        TextField_RUT.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        Label_Nombre1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Label_Nombre1.setText("Nombres");

        TextField_Nombre1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        Label_Direccion.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Label_Direccion.setText("Dirección");

        TextField_Direccion.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        Label_CodPostal.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Label_CodPostal.setText("Codigo Postal");

        Label_Telefono1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Label_Telefono1.setText("Dirección Web");

        TextField_Telefono1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        Label_Direccion1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Label_Direccion1.setText("E-Mail");

        TextField_Direccion1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        TextField_ApPaterno2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        Label_Telefono2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Label_Telefono2.setText("Teléfono/Movil");

        TextField_CodPostal1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        TextField_ApPaterno4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jButton1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton1.setText("Modificar");

        jButton2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton2.setText("Buscar");

        jButton3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton3.setText("Aceptar");

        jButton4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton4.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Label_Direccion))
                            .addComponent(TextField_Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Label_Telefono2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE))
                            .addComponent(TextField_Telefono1))
                        .addGap(18, 18, 18)
                        .addComponent(Label_CodPostal)
                        .addGap(216, 216, 216))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Label_Direccion1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(Label_Cliente))
                                    .addComponent(TextField_Direccion1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Label_Telefono1)
                                    .addComponent(TextField_CodPostal1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Label_RUT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextField_RUT, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Label_Nombre1)
                                    .addComponent(TextField_Nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Label_ApPaterno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TextField_ApPaterno2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Label_ApMaterno)
                                    .addComponent(TextField_ApPaterno4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(Label_Cliente)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_RUT)
                    .addComponent(TextField_RUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TextField_ApPaterno4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_ApPaterno)
                            .addComponent(Label_ApMaterno)
                            .addComponent(Label_Nombre1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextField_Nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextField_ApPaterno2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label_Direccion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextField_Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextField_Telefono1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Label_Telefono2)
                    .addComponent(Label_CodPostal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label_Direccion1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextField_Direccion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label_Telefono1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextField_CodPostal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_ApMaterno;
    private javax.swing.JLabel Label_ApPaterno;
    private javax.swing.JLabel Label_Cliente;
    private javax.swing.JLabel Label_CodPostal;
    private javax.swing.JLabel Label_Direccion;
    private javax.swing.JLabel Label_Direccion1;
    private javax.swing.JLabel Label_Nombre1;
    private javax.swing.JLabel Label_RUT;
    private javax.swing.JLabel Label_Telefono1;
    private javax.swing.JLabel Label_Telefono2;
    private javax.swing.JTextField TextField_ApPaterno2;
    private javax.swing.JTextField TextField_ApPaterno4;
    private javax.swing.JTextField TextField_CodPostal1;
    private javax.swing.JTextField TextField_Direccion;
    private javax.swing.JTextField TextField_Direccion1;
    private javax.swing.JTextField TextField_Nombre1;
    private javax.swing.JTextField TextField_RUT;
    private javax.swing.JTextField TextField_Telefono1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    // End of variables declaration//GEN-END:variables
}
