/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Validacion.ValidaCliente;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import Modelo.Cliente;

/**
 *
 * @author bastian
 */
public class Panel_ReVoluntaria2 extends javax.swing.JPanel {

    /**
     * Creates new form Panel_Cliente
     */
    public Panel_ReVoluntaria2() {
        initComponents();
    }
    
    private VentanaPrincipal V_Principal;
    
    public void setFrame(JFrame f){
        this.V_Principal= (VentanaPrincipal) f;
    }
    
    private void Limpiar(){
        this.TextField_ID.setText("");
        this.TextField_RUT.setText("");
        this.jTextField_Nombre.setText("");
        this.jTextField_Direccion.setText("");
        this.jDateChooser_Fecha.setDate(null);
    }
    
    public ArrayList getDatos(){
        ArrayList datos = new ArrayList();
        
        datos.add(this.TextField_ID.getText());
        datos.add(this.jDateChooser_Fecha.getDate());
        datos.add(this.jTextField_Direccion.getText());
        datos.add(this.jTextField_Nombre.getText());
        
        return datos;
    }
    
    protected void ReVoluntariaNueva(boolean b){
        this.Limpiar();
        this.TextField_ID.setEditable(!b);
        this.jButton_BuscarRec.setVisible(!b);
        this.jButton_ModificarRec.setVisible(!b);
        this.TextField_RUT.setEditable(b);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_Agregar = new javax.swing.JButton();
        TextField_RUT = new javax.swing.JTextField();
        jTextField_Nombre = new javax.swing.JTextField();
        jDateChooser_Fecha = new com.toedter.calendar.JDateChooser();
        jLabel_Nombre = new javax.swing.JLabel();
        TextField_ID = new javax.swing.JTextField();
        Label_RUT = new javax.swing.JLabel();
        jButton_BuscarRUT = new javax.swing.JButton();
        jLabel_Direccion = new javax.swing.JLabel();
        jTextField_Direccion = new javax.swing.JTextField();
        jButton_Aceptar = new javax.swing.JButton();
        jButton_Cancelar = new javax.swing.JButton();
        jLabel_ReVoluntaria = new javax.swing.JLabel();
        jButton_ModificarRec = new javax.swing.JButton();
        Label_ID = new javax.swing.JLabel();
        jLabel_FeIngreso = new javax.swing.JLabel();
        jButton_BuscarRec = new javax.swing.JButton();
        label_Justicia481 = new Vista.Imagenes_Label.justicia.Label_Justicia48();
        TextField_Rol = new javax.swing.JTextField();
        Label_Rol = new javax.swing.JLabel();
        jButton_BuscarCausa = new javax.swing.JButton();
        jButton_AgregarProductos = new javax.swing.JButton();
        jButton_BorrarProductos = new javax.swing.JButton();

        setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        setMaximumSize(new java.awt.Dimension(1000, 550));
        setMinimumSize(new java.awt.Dimension(1000, 550));
        setName("Cliente");
        setPreferredSize(new java.awt.Dimension(1000, 550));

        jButton_Agregar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton_Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes_Files/buscar_cliente/16.png"))); // NOI18N
        jButton_Agregar.setText("Agregar");

        TextField_RUT.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TextField_RUT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_RUTKeyTyped(evt);
            }
        });

        jTextField_Nombre.setEditable(false);
        jTextField_Nombre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jDateChooser_Fecha.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jDateChooser_Fecha.setMaxSelectableDate(new java.util.Date(253370779303000L));
        jDateChooser_Fecha.setMinSelectableDate(new java.util.Date(1262318503000L));
        jDateChooser_Fecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jDateChooser_FechaKeyTyped(evt);
            }
        });

        jLabel_Nombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel_Nombre.setText("Nombre");

        TextField_ID.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TextField_ID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_IDKeyTyped(evt);
            }
        });

        Label_RUT.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Label_RUT.setText("RUT");

        jButton_BuscarRUT.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton_BuscarRUT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes_Files/buscar/16.png"))); // NOI18N
        jButton_BuscarRUT.setText("Buscar");

        jLabel_Direccion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel_Direccion.setText("Dirección");

        jTextField_Direccion.setEditable(false);
        jTextField_Direccion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jButton_Aceptar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton_Aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes_Files/tick/16.png"))); // NOI18N
        jButton_Aceptar.setText("Aceptar");
        jButton_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AceptarActionPerformed(evt);
            }
        });

        jButton_Cancelar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes_Files/cruz/16.png"))); // NOI18N
        jButton_Cancelar.setText("Cancelar");
        jButton_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelarActionPerformed(evt);
            }
        });

        jLabel_ReVoluntaria.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel_ReVoluntaria.setText("Recepcion Voluntaria");

        jButton_ModificarRec.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton_ModificarRec.setText("Modificar");

        Label_ID.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Label_ID.setText("ID Recepción");

        jLabel_FeIngreso.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel_FeIngreso.setText("Fecha Ingreso");

        jButton_BuscarRec.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton_BuscarRec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes_Files/buscar/16.png"))); // NOI18N
        jButton_BuscarRec.setText("Buscar");

        TextField_Rol.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TextField_Rol.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_RolKeyTyped(evt);
            }
        });

        Label_Rol.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Label_Rol.setText("ROL Causa");

        jButton_BuscarCausa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton_BuscarCausa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes_Files/buscar/16.png"))); // NOI18N
        jButton_BuscarCausa.setText("Buscar");

        jButton_AgregarProductos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton_AgregarProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes_Files/producto/24.png"))); // NOI18N
        jButton_AgregarProductos.setText("Añadir Productos");

        jButton_BorrarProductos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton_BorrarProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes_Files/no_disponible/24.png"))); // NOI18N
        jButton_BorrarProductos.setText("Borrar todos los productos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_FeIngreso)
                                .addGap(10, 10, 10)
                                .addComponent(jDateChooser_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Label_RUT)
                                .addGap(83, 83, 83)
                                .addComponent(TextField_RUT, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_BuscarRUT)
                                .addGap(10, 10, 10)
                                .addComponent(jButton_Agregar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_Nombre)
                                .addGap(54, 54, 54)
                                .addComponent(jTextField_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_Direccion)
                                .addGap(44, 44, 44)
                                .addComponent(jTextField_Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Label_ID)
                                    .addComponent(Label_Rol))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextField_Rol)
                                    .addComponent(TextField_ID, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton_BuscarRec)
                                        .addGap(6, 6, 6)
                                        .addComponent(jButton_ModificarRec))
                                    .addComponent(jButton_BuscarCausa)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(jButton_AgregarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_BorrarProductos)))
                        .addGap(0, 183, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_Aceptar)
                        .addGap(9, 9, 9)
                        .addComponent(jButton_Cancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_ReVoluntaria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label_Justicia481, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_ReVoluntaria)
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(Label_ID))
                            .addComponent(TextField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_BuscarRec)
                            .addComponent(jButton_ModificarRec)))
                    .addComponent(label_Justicia481, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextField_Rol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_Rol)
                    .addComponent(jButton_BuscarCausa))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel_FeIngreso))
                    .addComponent(jDateChooser_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(Label_RUT))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(TextField_RUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(43, 43, 43)
                            .addComponent(jButton_BuscarRUT))))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel_Nombre))
                    .addComponent(jTextField_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel_Direccion))
                    .addComponent(jTextField_Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_AgregarProductos)
                    .addComponent(jButton_BorrarProductos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Aceptar)
                    .addComponent(jButton_Cancelar))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BuscarActionPerformed
        // TODO add your handling code here:
        V_Principal.addPanel_BuscaCliente(1);
    }//GEN-LAST:event_jButton_BuscarActionPerformed

    private void TextField_RUTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_RUTKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_RUTKeyTyped

    private void jDateChooser_FechaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDateChooser_FechaKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != '-') {
            evt.consume();
        }
    }//GEN-LAST:event_jDateChooser_FechaKeyTyped

    private void TextField_IDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_IDKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (!Character.isDigit(c) || this.TextField_ID.getText().length() > 10) {
            evt.consume();
        }
    }//GEN-LAST:event_TextField_IDKeyTyped

    private void jButton_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AceptarActionPerformed
        // TODO add your handling code here:
        //ENVIAR INFORMACION
    }//GEN-LAST:event_jButton_AceptarActionPerformed

    private void jButton_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelarActionPerformed
        // TODO add your handling code here:
        this.Limpiar();
        V_Principal.removePanel_ReVoluntaria();
    }//GEN-LAST:event_jButton_CancelarActionPerformed

    private void TextField_RolKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_RolKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_RolKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_ID;
    private javax.swing.JLabel Label_RUT;
    private javax.swing.JLabel Label_Rol;
    private javax.swing.JTextField TextField_ID;
    private javax.swing.JTextField TextField_RUT;
    private javax.swing.JTextField TextField_Rol;
    private javax.swing.JButton jButton_Aceptar;
    private javax.swing.JButton jButton_Agregar;
    private javax.swing.JButton jButton_AgregarProductos;
    private javax.swing.JButton jButton_BorrarProductos;
    private javax.swing.JButton jButton_BuscarCausa;
    private javax.swing.JButton jButton_BuscarRUT;
    private javax.swing.JButton jButton_BuscarRec;
    private javax.swing.JButton jButton_Cancelar;
    private javax.swing.JButton jButton_ModificarRec;
    private com.toedter.calendar.JDateChooser jDateChooser_Fecha;
    private javax.swing.JLabel jLabel_Direccion;
    private javax.swing.JLabel jLabel_FeIngreso;
    private javax.swing.JLabel jLabel_Nombre;
    private javax.swing.JLabel jLabel_ReVoluntaria;
    private javax.swing.JTextField jTextField_Direccion;
    private javax.swing.JTextField jTextField_Nombre;
    private Vista.Imagenes_Label.justicia.Label_Justicia48 label_Justicia481;
    // End of variables declaration//GEN-END:variables
}
