/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author bastian
 */
public class Panel_Remate extends javax.swing.JPanel {

    /**
     * Creates new form Panel_Remate
     */
    public Panel_Remate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Remate = new javax.swing.JLabel();
        jButton_Modificar = new javax.swing.JButton();
        TextField_ID = new javax.swing.JTextField();
        Label_ID = new javax.swing.JLabel();
        jButton_Buscar = new javax.swing.JButton();
        jLabel_Lugar = new javax.swing.JLabel();
        jTextField_Lugar = new javax.swing.JTextField();
        jTextField_Diario = new javax.swing.JTextField();
        jLabel_Diario = new javax.swing.JLabel();
        jTextField_Fecha = new javax.swing.JTextField();
        jLabel_Fecha = new javax.swing.JLabel();
        jTextField_Comision = new javax.swing.JTextField();
        jLabel_Comision = new javax.swing.JLabel();
        jTextField_Cuidad = new javax.swing.JTextField();
        jLabel_Ciudad = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Descripcion = new javax.swing.JTextArea();
        jLabel_Descripcion = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));

        jLabel_Remate.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel_Remate.setText("Remate");

        jButton_Modificar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton_Modificar.setText("Modificar");

        TextField_ID.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        Label_ID.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Label_ID.setText("ID");

        jButton_Buscar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton_Buscar.setText("Buscar");

        jLabel_Lugar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel_Lugar.setText("Lugar");

        jTextField_Lugar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jTextField_Diario.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel_Diario.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel_Diario.setText("Diario");

        jTextField_Fecha.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel_Fecha.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel_Fecha.setText("Fecha");

        jTextField_Comision.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel_Comision.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel_Comision.setText("Comisión");

        jTextField_Cuidad.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel_Ciudad.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel_Ciudad.setText("Ciudad");

        jTextArea_Descripcion.setColumns(20);
        jTextArea_Descripcion.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextArea_Descripcion.setRows(5);
        jScrollPane1.setViewportView(jTextArea_Descripcion);

        jLabel_Descripcion.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel_Descripcion.setText("Descripción (máximo 1000 caracteres)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Remate)
                            .addComponent(jLabel_Descripcion)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel_Lugar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField_Lugar, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel_Ciudad)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_Cuidad, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_Diario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_Diario, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_Comision)
                                    .addComponent(jLabel_Fecha))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_Comision, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Label_ID)
                                .addGap(52, 52, 52)
                                .addComponent(TextField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jButton_Buscar)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_Modificar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Remate)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(Label_ID))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(TextField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton_Buscar)
                    .addComponent(jButton_Modificar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Lugar)
                    .addComponent(jTextField_Lugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Diario)
                    .addComponent(jTextField_Diario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Fecha)
                    .addComponent(jTextField_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Comision)
                    .addComponent(jTextField_Comision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Ciudad)
                    .addComponent(jTextField_Cuidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel_Descripcion)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_ID;
    private javax.swing.JTextField TextField_ID;
    private javax.swing.JButton jButton_Buscar;
    private javax.swing.JButton jButton_Modificar;
    private javax.swing.JLabel jLabel_Ciudad;
    private javax.swing.JLabel jLabel_Comision;
    private javax.swing.JLabel jLabel_Descripcion;
    private javax.swing.JLabel jLabel_Diario;
    private javax.swing.JLabel jLabel_Fecha;
    private javax.swing.JLabel jLabel_Lugar;
    private javax.swing.JLabel jLabel_Remate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_Descripcion;
    private javax.swing.JTextField jTextField_Comision;
    private javax.swing.JTextField jTextField_Cuidad;
    private javax.swing.JTextField jTextField_Diario;
    private javax.swing.JTextField jTextField_Fecha;
    private javax.swing.JTextField jTextField_Lugar;
    // End of variables declaration//GEN-END:variables
}
