/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Buscador.java
 *
 * Created on 20-ene-2012, 20:24:19
 */
package Vista;

import Modelo.Busqueda;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Deico
 */

public class Panel_Busqueda extends javax.swing.JPanel {

    DefaultTableModel model = new DefaultTableModel();
    DefaultTableModel tmodel_cliente = new DefaultTableModel();
    DefaultTableModel tmodel_factura = new DefaultTableModel();
    DefaultTableModel tmodel_remate = new DefaultTableModel();
    DefaultTableModel tmodel_producto = new DefaultTableModel();
    DefaultTableModel tmodel_causa = new DefaultTableModel();
    DefaultTableModel tmodel_recepcion_judicial = new DefaultTableModel();
    DefaultTableModel tmodel_recepcion_voluntaria = new DefaultTableModel();
    
    /** Creates new form Buscador */
    
    public Panel_Busqueda() {
        initComponents();
        initTableModels();
        model = tmodel_cliente;
        Tabla.setModel(model);
        Modelo.Busqueda.initClientes();
       
    }

    private void initTableModels(){
        
        tmodel_cliente.addColumn("RUT");
        tmodel_cliente.addColumn("Apellido P");
        tmodel_cliente.addColumn("Apellido M");
        tmodel_cliente.addColumn("Nombre");
        tmodel_cliente.addColumn("Telefono");
        tmodel_cliente.addColumn("Direccion");
        tmodel_cliente.addColumn("Email");
        
        tmodel_factura.addColumn("Factura");
        tmodel_factura.addColumn("Rut");
        tmodel_factura.addColumn("Apellido P");
        tmodel_factura.addColumn("Apellido M");
        tmodel_factura.addColumn("Nombre");
        tmodel_factura.addColumn("Total");
        tmodel_factura.addColumn("Garantia");
        tmodel_factura.addColumn("Fecha");
        tmodel_factura.addColumn("Estado");
        tmodel_factura.addColumn("Exento");
        tmodel_factura.addColumn("Neto");
        tmodel_factura.addColumn("Impuestos");
        tmodel_factura.addColumn("Comision");
        tmodel_factura.addColumn("IVA");
        tmodel_factura.addColumn("Comison factura");
        
        tmodel_remate.addColumn("RUT");
        tmodel_remate.addColumn("Nombre");
        tmodel_remate.addColumn("Telefono");
        tmodel_remate.addColumn("Direccion");
        tmodel_remate.addColumn("Id factura");
        tmodel_remate.addColumn("Total Factura");
        
        tmodel_producto.addColumn("Lote");
        tmodel_producto.addColumn("ID REMATE");
        tmodel_producto.addColumn("Descripcion");
        tmodel_producto.addColumn("Cantidad");
        tmodel_producto.addColumn("Precio");
        tmodel_producto.addColumn("Total");
        tmodel_producto.addColumn("Garantia");
        
        tmodel_causa.addColumn("ROL");
        tmodel_causa.addColumn("Receptor");
        tmodel_causa.addColumn("Abogado");
        tmodel_causa.addColumn("Caratulado como");
        tmodel_causa.addColumn("Juzgado");
        tmodel_causa.addColumn("Remate");
        tmodel_causa.addColumn("ID RJ");
              
        tmodel_recepcion_judicial.addColumn("ROL");
        tmodel_recepcion_judicial.addColumn("ID_RJ");
        tmodel_recepcion_judicial.addColumn("ID PRODUCTO");
        tmodel_recepcion_judicial.addColumn("Descripcion Producto");
        tmodel_recepcion_judicial.addColumn("Garantia");
        tmodel_recepcion_judicial.addColumn("Total");
        
        
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parametro_busqueda = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Campo = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();

        parametro_busqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parametro_busquedaActionPerformed(evt);
            }
        });
        parametro_busqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                parametro_busquedaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                parametro_busquedaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                parametro_busquedaKeyTyped(evt);
            }
        });

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Campo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cliente",
            "Factura", "Remate", "Causa" ,"Producto", "Recepcion Judicial", "Recepcion Voluntaria"}));
Campo.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        CampoActionPerformed(evt);
    }
    });

    jLabel1.setText("Modo de Busqueda");

    Tabla.setModel(model);
    jScrollPane1.setViewportView(Tabla);

    jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

    jLabel2.setText("Campo a buscar");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(parametro_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Campo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel2)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel1))
                        .addComponent(jButton1))))
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(Campo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel1)
                .addComponent(jLabel2))
            .addGap(16, 16, 16)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(parametro_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton1))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
            .addContainerGap())
    );
    }// </editor-fold>//GEN-END:initComponents

private void parametro_busquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_parametro_busquedaKeyReleased
// TODO add your handling code here:
     
  int campo = this.Campo.getSelectedIndex();
   if(campo==0){
       if(!parametro_busqueda.getText().isEmpty()){
          cleanModel(model);
          Busqueda.busca_cliente(parametro_busqueda.getText().toLowerCase(),model);
    }
   }
   else if(campo==1){
       if(!parametro_busqueda.getText().isEmpty()){
          cleanModel(model);
          Busqueda.busqueda_factura(parametro_busqueda.getText().toLowerCase(),model);
    }
   }
   else if(campo==2){
       if(!parametro_busqueda.getText().isEmpty()){
          cleanModel(model);
         if(Modelo.Remate.isRemate(parametro_busqueda.getText().toUpperCase()))
          Busqueda.busqueda_remate(parametro_busqueda.getText().toLowerCase(),model);
    }
   }
   else if(campo==3){
    
       if(!parametro_busqueda.getText().isEmpty()){
          cleanModel(model);
          Busqueda.busqueda_causa(parametro_busqueda.getText().toUpperCase(),model);
    }
       
   }
   else if(campo==4){
      
        if(!parametro_busqueda.getText().isEmpty()){
          cleanModel(model);
          Busqueda.busqueda_producto(parametro_busqueda.getText().toLowerCase(),model);
    }
   }
    else if(campo==5){
      
        if(!parametro_busqueda.getText().isEmpty()){
          cleanModel(model);
          Busqueda.busqueda_recepcion_judicial(parametro_busqueda.getText().toUpperCase(),model);
    }
    
   }
   
   
}//GEN-LAST:event_parametro_busquedaKeyReleased

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
      
    
}//GEN-LAST:event_jButton1ActionPerformed

private void parametro_busquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_parametro_busquedaKeyPressed
// TODO add your handling code here:
    
   
}//GEN-LAST:event_parametro_busquedaKeyPressed

private void parametro_busquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_parametro_busquedaKeyTyped
// TODO add your handling code here:
     
}//GEN-LAST:event_parametro_busquedaKeyTyped

private void CampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoActionPerformed
// TODO add your handling code here:
   int campo = this.Campo.getSelectedIndex();
   if(campo==0){
       model = tmodel_cliente;
       Tabla.setModel(model);
   }
   else if(campo==1){
       model = tmodel_factura;
       Tabla.setModel(model);
   }
   else if(campo==2){
       model = tmodel_remate;
       Tabla.setModel(model);
   }
   else if(campo==3){
       model = tmodel_causa;
       Tabla.setModel(model);
   }
   else if(campo==4){
       model = tmodel_producto;
       Tabla.setModel(model);
   }
   else if(campo==5){
       model = tmodel_recepcion_judicial;
       Tabla.setModel(model);
   }
   
}//GEN-LAST:event_CampoActionPerformed

private void parametro_busquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parametro_busquedaActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_parametro_busquedaActionPerformed

public void cleanModel(DefaultTableModel model){
    int a =model.getRowCount()-1;

    for (int i = a; i >=0; i--) {
        model.removeRow(i);
        
    }

    
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Campo;
    private javax.swing.JTable Tabla;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField parametro_busqueda;
    // End of variables declaration//GEN-END:variables
}
